---
name: Deploy site

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: npm install
      - name: Configures Git
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${git_email}"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          git_email: "${{ github.actor }}@users.noreply.github.com"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy site
        run: |
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          NODE_DEBUG: gh-pages
